# Generated by Django 2.2 on 2020-09-10 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('industrial_project_app', '0002_auto_20200910_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(null=True, upload_to='')),
                ('Text', models.TextField(null=True)),
                ('CreatedDate', models.DateField()),
                ('UpdateDate', models.DateField()),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='posted',
            new_name='CreatedDate',
        ),
        migrations.RemoveField(
            model_name='post',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='Post_Title',
            field=models.CharField(default=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='industrial_project_app.User_Table'), max_length=50),
        ),
        migrations.AddField(
            model_name='post',
            name='UpdateDate',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='User',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='industrial_project_app.User_Table'),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='post',
            name='Post_Content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='industrial_project_app.Content'),
        ),
    ]
